concurrency: 5
development:
  :pidfile: /var/app/shared/tmp/pids/sidekiq.pid
  :logfile: /var/app/shared/log/sidekiq_development.log
staging:
  :pidfile: /var/app/shared/tmp/pids/sidekiq.pid
  :logfile: /var/app/shared/log/sidekiq_staging.log
production:
  :pidfile: /var/app/shared/tmp/pids/sidekiq.pid
  :logfile: /var/app/shared/log/sidekiq_production.log
  :concurrency: 50
